// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PropertySet } from '../fragments/property-set.js';


export class Item {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Item {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsItem(bb:flatbuffers.ByteBuffer, obj?:Item):Item {
  return (obj || new Item()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsItem(bb:flatbuffers.ByteBuffer, obj?:Item):Item {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Item()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

expressId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

globalId():string|null
globalId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
globalId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ifcType():string|null
ifcType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ifcType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

properties(index: number, obj?:PropertySet):PropertySet|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new PropertySet()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

propertiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

geometryIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startItem(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addExpressId(builder:flatbuffers.Builder, expressId:number) {
  builder.addFieldInt32(0, expressId, 0);
}

static addGlobalId(builder:flatbuffers.Builder, globalIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, globalIdOffset, 0);
}

static addIfcType(builder:flatbuffers.Builder, ifcTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ifcTypeOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nameOffset, 0);
}

static addProperties(builder:flatbuffers.Builder, propertiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, propertiesOffset, 0);
}

static createPropertiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPropertiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addGeometryIndex(builder:flatbuffers.Builder, geometryIndex:number) {
  builder.addFieldInt32(5, geometryIndex, 0);
}

static endItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createItem(builder:flatbuffers.Builder, expressId:number, globalIdOffset:flatbuffers.Offset, ifcTypeOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, propertiesOffset:flatbuffers.Offset, geometryIndex:number):flatbuffers.Offset {
  Item.startItem(builder);
  Item.addExpressId(builder, expressId);
  Item.addGlobalId(builder, globalIdOffset);
  Item.addIfcType(builder, ifcTypeOffset);
  Item.addName(builder, nameOffset);
  Item.addProperties(builder, propertiesOffset);
  Item.addGeometryIndex(builder, geometryIndex);
  return Item.endItem(builder);
}
}
