// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class SpatialNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpatialNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpatialNode(bb:flatbuffers.ByteBuffer, obj?:SpatialNode):SpatialNode {
  return (obj || new SpatialNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpatialNode(bb:flatbuffers.ByteBuffer, obj?:SpatialNode):SpatialNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpatialNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

expressId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

globalId():string|null
globalId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
globalId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ifcType():string|null
ifcType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ifcType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

children(index: number, obj?:SpatialNode):SpatialNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new SpatialNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

childrenLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

elementIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

elementIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

elementIdsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startSpatialNode(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addExpressId(builder:flatbuffers.Builder, expressId:number) {
  builder.addFieldInt32(0, expressId, 0);
}

static addGlobalId(builder:flatbuffers.Builder, globalIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, globalIdOffset, 0);
}

static addIfcType(builder:flatbuffers.Builder, ifcTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ifcTypeOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nameOffset, 0);
}

static addChildren(builder:flatbuffers.Builder, childrenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, childrenOffset, 0);
}

static createChildrenVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChildrenVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addElementIds(builder:flatbuffers.Builder, elementIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, elementIdsOffset, 0);
}

static createElementIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createElementIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createElementIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startElementIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSpatialNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSpatialNode(builder:flatbuffers.Builder, expressId:number, globalIdOffset:flatbuffers.Offset, ifcTypeOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, childrenOffset:flatbuffers.Offset, elementIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SpatialNode.startSpatialNode(builder);
  SpatialNode.addExpressId(builder, expressId);
  SpatialNode.addGlobalId(builder, globalIdOffset);
  SpatialNode.addIfcType(builder, ifcTypeOffset);
  SpatialNode.addName(builder, nameOffset);
  SpatialNode.addChildren(builder, childrenOffset);
  SpatialNode.addElementIds(builder, elementIdsOffset);
  return SpatialNode.endSpatialNode(builder);
}
}
